DUCK_FACTS = [
    "Ducks have waterproof feathers.",
    "The oldest known duck was 35 years old.",
    "Ducks have been domesticated for more than 4,000 years.",
    "A male duck is called a drake, a female duck a hen, and a baby duck a duckling.",
    "Ducks have three eyelids: upper, lower, and a third transparent eyelid for swimming.",
    "When ducks clean themselves, it is called 'preening.' They use their bills to clean between their feathers.",
    "Most duck eggs hatch within 28 days.",
    "Ducklings can fly within 5-8 weeks of hatching.",
    "Ducks waddle due to their webbed feet.",
    "Ducks cannot feel cold in their feet because their feet have no nerves or blood vessels.",
    "There are different types of ducks, including diving ducks, sea ducks, and dabbling ducks.",
    "Ducks are social animals and prefer to be in groups.",
    "Pet ducks can live up to 20 years if well cared for.",
    "Ducks lay more eggs when there is more daylight.",
    "Ducks have three eyelids and can see in color.",
    "Ducks can communicate with each other before hatching.",
    "Ducks can sleep with one eye open to watch for predators.",
    "Duckbills are sensitive, similar to human fingertips.",
    "Ducklings have abstract thought capabilities.",
    "Ducks may have a preference for green or blue colors.",
    "Ducks use up to 12,000 separate muscles to control their feathers.",
    "Some ducks, like wood ducks, can raise two broods in one year.",
    "Ducks sometimes practice nest parasitism by laying eggs in other ducks' nests.",
    "Ducks are found on every continent except Antarctica.",
    "Ducks are omnivores and have a varied diet including plants, insects, and small fish.",
    "Ducks have a gland that produces oil to keep their feathers waterproof.",
    "Ducks are born precocial, meaning they can walk, swim and feed themselves shortly after hatching.",
    "Some ducks, like the ruddy duck, can lay large eggs relative to their body size.",
    "Wild ducks typically live for 5-10 years.",
]

DUCK_JOKES = [
    "What do ducks use to surf the internet? Quackernet.",
    "Why did the duck bring a towel? In case it got wet!",
    "What do you call a duck that's a great chef? A master quacker.",
    "Why don't ducks ever lose at games? Because they always have a bill of luck!",
    "What did the duck say to the bartender? 'Put it on my bill.'",
    "Why are ducks so good at basketball? They always make quacking shots.",
    "What’s a duck’s favorite snack? Cheese and quackers.",
    "Why did the duck stay home from work? It felt a little under the feather.",
    "How do ducks communicate with each other? They quack their messages.",
    "What do you get when you cross a duck with fireworks? Firequackers!",
    "Why did the duck sit in the shade? Because it was a hot quack.",
    "What do you call a duck detective? Quack Holmes.",
    "Why did the duck wear a raincoat? Because it heard the weather was going to be fowl.",
    "What did the duck say when it bought lipstick? 'Put it on my bill.'",
    "Why did the duck go to space? To explore the quackstronaut frontier.",
    "What's a duck's favorite vegetable? Quack-o-lantern.",
    "What do ducks read to their ducklings? Quacktional stories.",
    "How do ducks like to pay? They prefer to use their bill.",
    "What does a duck say after a joke? 'Quack up!'",
    "Why did the duck play football? Because it wanted to be a quacker-back.",
    "What kind of TV shows do ducks like? Duck-umentaries.",
    "Why did the duck cross the playground? To get to the other slide.",
    "What did the duck say when it finished its meal? 'That was absolutely quacktastic!'",
    "Why do ducks never get lost? They always follow their quack sense.",
    "What’s a duck’s favorite game? Duck, Duck, Goose!",
    "What did the duck say to the comedian? 'You really quack me up!'",
    "Why did the duck sit in the refrigerator? To get its quack together.",
    "How do ducks like their eggs? Quack poached.",
    "What do ducks do at a party? They quack up the dance floor.",
    "What kind of music do ducks like? Quack 'n' roll.",
    "Why are ducks great at building things? They're good with duck tape.",
    "What's a duck’s favorite game to play with kids? Quack-a-mole.",
    "Why did the duck bring a suitcase to the pond? It was going on a quackation.",
    "What do you call a clever duck? A wise quack.",
    "What did the duck say when it broke its bill? 'I quack under pressure.'",
    "What do ducks do when they're bored? They go for a quack-walk.",
    "Why did the duck fail its driving test? It couldn’t quack under pressure.",
    "What do ducks like to play on the piano? Beak-ethoven.",
    "Why do ducks love the internet? They’re big fans of quack streams.",
    "What’s a duck’s favorite place to visit? The quack museum.",
    "What do you get if you cross a duck with a comedian? A quack-up.",
    "Why did the duck call the insurance company? It had a fowl claim.",
    "What do ducks do on a date? They go out for a quacking good time.",
    "Why was the duck put in time-out? It was being too quacky.",
    "What's a duck's favorite car? A Volkswagen QuackBeetle.",
    "Why do ducks make good bankers? They have a lot of bills.",
    "What’s a duck’s favorite holiday? Quack-o-ween.",
]
